name: pipeline3
on:
  push:
    branches:
      - staging

env:
  APP_NAME: angularapp
  NODE_VERSION: "18"
  USERNAME: hghrayeb96
  PASSWORD: 71260870Hh

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    
      - name: clone repository
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          version: ${{ env.NODE_VERSION  }}

      - name: install dependencies
        run: npm ci

      - name: build in dev mode
        run: ng build

      - name: create docker image and push
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: build docker image
        run: docker build -t angular-app-latest:1.0.0 -f Dockerfile.prod . && docker tag angular-app-latest:1.0.0 hasanghrayeb/angular-app:1.0.0 && docker push hasanghrayeb/angular-app:1.0.0   
      
